# Generated by Django 3.1.2 on 2022-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50, unique=True)),
                ('campaign_intent', models.CharField(max_length=50)),
                ('campaign_desc', models.CharField(max_length=250)),
                ('kpi_event', models.CharField(max_length=50)),
                ('user_percentage', models.FloatField()),
                ('performance_ctr', models.FloatField(default=0.0)),
                ('performance_cvr', models.FloatField(default=0.0)),
                ('campaign_status', models.CharField(default='Scheduled', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projected_matrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_percentage', models.FloatField(default=0.0)),
                ('ctr', models.FloatField(default=0.0)),
                ('cvr', models.FloatField(default=0.0)),
            ],
        ),
    ]
